changed groupId of android-maven-plugin and upgraded to 4.1.1 in order to avoid `java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State` and changed project structure in order to avoid failure or the need to specify non-standard parameters